package com.example.betting.mock;

import com.example.betting.user.domain.User;
import com.example.betting.user.service.port.UserRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeUserRepository implements UserRepository {

    private long autoGeneratedId = 0;
    private final List<User> data = new ArrayList<>();

    @Override
    public Optional<User> getUser(Long id) {
        return data.stream().filter(item -> item.getId() == id).findAny();
    }

    @Override
    public List<User> list() {
        return data;
    }

    @Override
    public User save(User user) {
        if(user.getId() == null || user.getId() == 0){
            User newUser = User.builder()
                    .id(++autoGeneratedId)
                    .username(user.getUsername())
                    .password(user.getPassword())
                    .email(user.getEmail())
                    .age(user.getAge())
                    .build();
            data.add(newUser);
            return newUser;
        }else {
            if(autoGeneratedId < user.getId())
                autoGeneratedId = user.getId();
            data.removeIf(item -> item.getId() == user.getId());
            data.add(user);
            return user;
        }
    }
}
