package com.example.betting.mock;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;

import com.example.betting.ship.domain.Ship;
import com.example.betting.ship.service.port.ShipRepository;

public class FakeShipRepository implements ShipRepository {

    private long autoGeneratedId = 0;
    private final List<Ship> data = new ArrayList<>();
    
    @Override
    public List<Ship> findAll() {
        return data;
    }

    @Override
    public Optional<Ship> findById(Long id) {
        return data.stream().filter(item -> item.getShipId() == id).findAny();
    }

    @Override
    public Ship save(Ship ship) {
        if (ship.getShipId() == 0) {
            Ship newShip = Ship.builder()
                .shipId(++autoGeneratedId)
                .name(ship.getName())
                .weight(ship.getWeight())
                .build();
            data.add(newShip);
            return newShip;
        } else {
            if (autoGeneratedId < ship.getShipId()) autoGeneratedId = ship.getShipId();
            data.removeIf(item -> item.getShipId() == ship.getShipId());
            data.add(ship);
            return ship;
        }
    }

    @Override
    public Optional<Ship> findByNameAndWeight(String name, int weight) {
        return data.stream().filter(item -> item.getName().equals(name) && item.getWeight() == weight).findAny();
    }

    @Override
    public List<Ship> search(String name) {
        return data.stream().filter(item -> item.getName().equals(name))
                            .sorted(Comparator.comparing(Ship::getShipId).reversed())
                            .limit(10)
                            // .skip(10)
                            .toList();
    }
    
}
